### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by apelt** [jnasmartcardio/jnasmartcardio#37]
When creating new TerminalFactory with following code:
`TerminalFactory factory =  TerminalFactory.getInstance("PC/SC", null, new jnasmartcardio.Smartcardio());`

a _ThreadLocal_ of type **_com.sun.jna.Structure_** is also created inside of the _Smartcardio_ object (thanks to creation of **_SCardReaderState_**'s **_Pointer_** object) 

The issue is that instantiation of _jnasmartcardio.Smartcardio_ results in memory leak on **Tomcat9** server with following error message, after shutting the server down via **./catalina.out stop** command:

_01-Jul-2020 11:28:34.146 SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [MyServiceProvider] created a ThreadLocal with key of type [com.sun.jna.Structure$2] (value [com.sun.jna.Structure$2@6cd98a05]) and a value of type [com.sun.jna.Structure.StructureSet] (value [[]]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak._

I cannot access the _com.sun.jna_ package of _jnasmartcardio_ from my own app, so I implemented the Maven dependency directly in my project in pom.xml:

		_
		<dependency>
			<groupId>net.java.dev.jna</groupId>
			<artifactId>jna</artifactId>
			<version>5.4.0</version>
		</dependency>_

This allowed me to call _com.sun.jna.Memory.disposeAll()_ inside of _destroy()_ method of my Java Servlet. However, the memory leak still occurs.

**Comment by martinpaljak** [comment]
Why do you run (local) smart cards in a webapp? :)

Anyway, AFAIU the issue here is that something is not cleaned up. My quick grep did not reveal ThreadLocal usage at all in jnasmartcardio, to be able to explicitly free something?

**Comment by apelt** [comment]
Hi,
well on the server, there is a SAM cluster (lots of SAM cards). When mobile client app connects, the web app searches for available SAM card which is not currently in usage by another client and connects the client to it for APDU exchange. The client is connected on its side also to a Smart Card (or Secure Element) via NFC.
So the Smart Card at client side communicates with the SAM Card on server side via a mobile terminal.

When I was looking for the solution to get rid of the memory leak (after searching the whole internet) I commented pieces of the source code. In the end I found out that If I comment this line:
`TerminalFactory factory = TerminalFactory.getInstance("PC/SC", null, new jnasmartcardio.Smartcardio());`
or use instead of it this:
`TerminalFactory factory =  TerminalFactory.getDefault();`

The memory leak does not occur anymore. Unfortunately, the _TerminalFactory.getDefault()_ is not an option for me as it causes different issues, when the communication with SAM card is not possible at all.

 So I took a look inside of **Smartcardio** class and I found out that it uses **SCardReaderState** class which extends **Structure** class. The memory leak message above says "_...ThreadLocal with key of type [**com.sun.jna.Structure**$2] ...  probable memory leak._"

I can also see that the **SCardReaderState** uses com.sun.jna.**Pointer**. In following link:
[https://stackoverflow.com/questions/33307311/is-there-a-memory-leak-issue-with-using-jnas-memory-class](https://stackoverflow.com/questions/33307311/is-there-a-memory-leak-issue-with-using-jnas-memory-class)
the accepted answer suggests to use _Memory.disposeAll()_ but that is not working. I am not familiar with jnasmartcardio very well, but I guess the jnasmartcardio would have to use **Memory** instead of **Pointer** class... (the Memory class extends the Pointer class)

**Comment by apelt** [comment]
Maybe it is a platform specific. Here:
[https://github.com/ReactiveX/RxJava/issues/1730](https://github.com/ReactiveX/RxJava/issues/1730)
They were solving similar issue in case of RxJava tasks, which were causing also memory leaks to me. RxJava added method **Schedulers.shutdown()** and the leaks do not occur anymore, when this is used inside of  destroy() method of my Java Servlet.

When using RxJava on other platforms, like Android, **Schedulers.shutdown()** was never needed to be called.

**Comment by apelt** [comment]
Well, it is actually problem of _**com.sun.jna**_ as it is coming from there, not from **_jnasmartcardio_**. Therefore, I will close the issue here.

**Comment by martinpaljak** [comment]
well, if there is something jnasmartcardio can do/call from jna at a specific time, it can and should be fixed here. But it would be nice if somebody came up with a patch :)
