### ISSUE TITLE
SCARD_E_INVALID_HANDLE on SCardConnect

### ISSUE THREAD

**Issue by suzukieng** [jnasmartcardio/jnasmartcardio#9]
I am getting the following exception on OS X 10.8 and 10.9, using the latest master:

```
Caused by: jnasmartcardio.Smartcardio$JnaPCSCException: SCardConnect got response 0xffffffff80100003 (SCARD_E_INVALID_HANDLE: The supplied handle was invalid.)
    at jnasmartcardio.Smartcardio.check(Smartcardio.java:920)
    at jnasmartcardio.Smartcardio.access$100(Smartcardio.java:35)
    at jnasmartcardio.Smartcardio$JnaCardTerminal.connect(Smartcardio.java:421)
    at 
```

Do you have an idea what might be causing this? I'm calling CardTerminals.waitForChange(0) and then listing the CardReaders that have CARD_INSERTION state, connecting to those cards, and reading a serial number. I'm doing this in an endless loop. The loop, along with the initialization, runs in a background thread.

I see some jnasmartcardio Output on System.out:

```
 INFO [CardManager$CardDiscoveryThread] (CardManager.java:55) - Background card discovery thread started
DEBUG [CardManager$CardDiscoveryThread] (AbstractSmartcardReader.java:96) - Waiting for changes...
0 -> 6 \\?PnP?\Notification
DEBUG [$CardDiscoveryThread] (AbstractSmartcardReader.java:96) - Waiting for changes...
6 -> 4 \\?PnP?\Notification
12 -> 22 SCM SCR 3310 00 00
 INFO [CardManager$CardDiscoveryThread] (AbstractSmartcardReader.java:100) - Card inserted in terminal: SCM SCR 3310 00 00
 WARN [CardManager$CardDiscoveryThread] (CardManager.java:77) - Failure while waiting for smartcards: jnasmartcardio.Smartcardio$JnaPCSCException: SCardConnect got response 0xffffffff80100003 (SCARD_E_INVALID_HANDLE: The supplied handle was invalid.)
at ...
```

The output looks a bit suspicious, as the first waitForChanges call completes instantly. 
Is there perhaps some problem with PnP notification? I tried setting the boolean member usePnp to false, but the issue still happens. Were there any recent changes that might be causing this behavior?
And last but not least, are there any threading constraints when using jnasmartcardio?

**Comment by martin-lizner** [comment]
Would you please paste code that solved SCARD_E_INVALID_HANDLE? Tnx
